language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed 
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  # Tagging
  - docker tag udagram-api-feed "$DOCKER_USERNAME"/udagram-api-feed:v2
  - docker tag udagram-api-user "$DOCKER_USERNAME"/udagram-api-user:v2
  - docker tag udagram-frontend "$DOCKER_USERNAME"/udagram-frontend:v2
  - docker tag reverseproxy "$DOCKER_USERNAME"/reverseproxy:v2

after_success:
  # Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/udagram-api-feed:v2
  - docker push "$DOCKER_USERNAME"/udagram-api-user:v2
  - docker push "$DOCKER_USERNAME"/udagram-frontend:v2
  - docker push "$DOCKER_USERNAME"/reverseproxy:v2