version: "3"
services:
  reverseproxy:
      image: docker.io/loveday515/reverseproxy:v1
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
      labels:
        kompose.service.type: LoadBalancer
  backend-user:
    image: docker.io/loveday515/udagram-api-user:v1
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: docker.io/loveday515/udagram-api-feed:v1
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: docker.io/loveday515/udagram-frontend:v1
    ports:
      - "8100:80"
    labels:
      kompose.service.type: LoadBalancer